---
- name: Add the OS specific varibles
  include_vars: "group_vars/{{ansible_distribution}}{{ansible_distribution_major_version}}.yml"

- debug: var=OLCSUFFIX
- debug: var=OLCROOTDN
- debug: var=OLCROOTPW

- name: ensure {{tmp_folder_targets}} folder exists
  file:
    path: "{{tmp_folder_targets}}"
    state: directory
    mode: 0777

- name: ensure {{tmp_folder_controller}} folder exists
  file:
    path: "{{tmp_folder_controller}}"
    state: directory
    mode: 0777
  delegate_to: 127.0.0.1

- name: Install wget
  yum: 
    pkg: "{{ item }}"
    state: present
  with_items:
     - wget


