---
- hosts: visual
  become: yes
  become_user: sas

  tasks:

  - name: Reset the sasboot password
    shell: |
      export host=localhost
      export code=$(ls -tr /var/log/sas/viya/saslogon/default/sas-saslogon_* | tail -n1 | grep '.log$' | xargs grep 'sasboot' | cut -d'=' -f2)
      # make the first request, this expands the link
      curl http://$host/SASLogon/reset_password?code=$code -c cookies -o output
      # get a few things out of the output to use in the next request
      export CSRF_TOKEN=$(grep 'name="_csrf"' output | cut -f 6 -d '"')
      export NEW_CODE=$(grep 'name="code"' output | cut -f 6 -d '"')
      # make the second request with the password and other information
      curl -b cookies http://$host/SASLogon/reset_password.do -H "Content-Type: application/x-www-form-urlencoded" -d "code=${NEW_CODE}&email=none&password={{sasboot_pw}}&password_confirmation={{sasboot_pw}}&_csrf=${CSRF_TOKEN}"
      exit 0
    args:
      executable: /bin/bash
    tags:
      - sasboot



