---
- hosts: sas-all
  become: yes

  vars:

    ## sasboot password ##
    sasboot_pw: lnxsas

  tasks:

  - name: display the status of each machine
    shell: "/etc/init.d/sas-viya-all-services status"
    register: status_check
    tags:
      - postdep
      - status_check

  - name: Display the status
    debug: var=status_check.stdout_lines
    tags:
      - postdep
      - status_check


  - name: capture memory consumption by microservice
    shell: "ps -e -orss=,args= | grep java | grep -v grep | sort -b -k1,1n | awk '{print $1/1024 \",\"  $NF}'"
    register: mem_cons
    tags:
      - postdep
      - mem

  - name: Display the result
    debug: var=mem_cons.stdout_lines
    tags:
      - postdep
      - mem


- hosts: CoreServices
  become: yes
  become_user: sas


  tasks:


## show the saslogon url to reset the sasboot password
  - name: copy the resetsasboot to the right machine
    copy:
      src: ./ansible.resetsasboot.sh
      dest: /tmp/resetsasboot.sh
      owner: sas
      group: sas
      mode: 0700
    tags:
      - postdep
      - sasboot

  - name: Reset the sasboot password
    shell: /tmp/resetsasboot.sh {{sasboot_pw}}
    tags:
      - postdep
      - sasboot

# only for EA - these files should already be there in production
- hosts:
  - sas-casserver-primary
  become: yes
  become_user: root

  tasks:

  - name: copy odbc resources (controller)
    shell: |
      systemctl stop sas-viya-cascontroller-default.service;
      tar xvf /tmp/accessclients.tar -C /opt/sas/viya/home/lib64;
      cp /tmp/tkeredsh.so /opt/sas/viya/home/SASFoundation/sasexe;
      chown sas:sas /opt/sas/viya/home/SASFoundation/sasexe/tkeredsh.so;
      systemctl start sas-viya-cascontroller-default.service
    tags:
      - EA

- hosts:
  - sas-casserver-worker
  become: yes
  become_user: root

  tasks:

  - name: copy odbc resources (workers)
    shell: |
      tar xvf /tmp/accessclients.tar -C /opt/sas/viya/home/lib64;
      cp /tmp/tkeredsh.so /opt/sas/viya/home/SASFoundation/sasexe;
      chown sas:sas /opt/sas/viya/home/SASFoundation/sasexe/tkeredsh.so;
    tags:
      - EA
