--- 
- hosts: localhost
    
  tasks:

  - name: remove default deployTarget
    replace:
      dest=inventory.ini
      regexp='\[host-definitions\]\ndeployTarget.*'
      replace='[host-definitions]'

  - name: insert host definitions
    blockinfile:
      insertafter='\[host-definitions\]'
      dest=inventory.ini
      block="{{ lookup('file', '/tmp/inventory.head') }}"

  - name: Set CAS controller target
    replace:
      dest=inventory.ini
      regexp='\[sas-casserver-primary\]\ndeployTarget'
      replace='[sas-casserver-primary]\ncontroller'
      backup=yes

      
