--- 
- hosts: localhost
    
  tasks:

  - name: create new inventory
    shell: tail -n +2 hosts > tmp.ini ; cat /tmp/inventory.head tmp.ini > inventory.ini



  - name: replace inventory in ansible.cfg
    lineinfile: 
      dest=ansible.cfg
      regexp='^inventory' 
      line='inventory = inventory.ini'
      backup=yes
      state=present

  - name: disable host key checking in ansible.cfg
    lineinfile:
       dest=ansible.cfg
       regexp='^host_key_checking'
       line='host_key_checking = false'
       backup=yes
       state=present

  - name: add ssh_connection label
    lineinfile:
      dest=ansible.cfg
      line='[ssh_connection]'
      state=present

  - name: add ssh retries - in cas the initialization of the other hosts is slow
    lineinfile:
      dest=ansible.cfg
      insertafter='^[ssh_connection]$'
      regexp="retries="
      line="retries=3"
      state=present


  - name: Set CAS controller target
    replace:
      dest=inventory.ini
      regexp='\[sas-casserver-primary\]\ndeployTarget'
      replace='[sas-casserver-primary]\ncontroller'
      backup=yes

      
#  - name: Update CAS Controller group
#    blockinfile:
#      dest: newinv.ini
#      marker: "# {mark} controller -->"
#      insertafter: '\[sas-casserver-primary\]'
#      content: |
#        auto_cc
#    tags:
#      - updateinventory
#
#  - name: Update CAS worker group
#    blockinfile:
#      dest: newinv.ini
#      marker: "# {mark} workers -->"
#      insertafter: '\[sas-casserver-worker\]'
#      content: |
#        auto_cw01
#        auto_cw02
#        auto_cw03
#    tags:
#      - updateinventory
#
#
#  - name: add stuff for mirror
#    blockinfile:
#      dest: newinv.ini
#      marker: "# {mark} mirror -->"
#      insertafter: EOF
#      content: |
#        [mirrorhost]
#        auto_supp
#
#        [repohost]
#        auto_supp
#    tags:
#      - updateinventory
#
#
      